"""M1

Revision ID: 99307b83d06b
Revises: 
Create Date: 2025-02-05 07:48:45.703541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99307b83d06b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_copy')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('client_id_seq'::regclass)"))

    with op.batch_alter_table('consist', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('consist_id_seq'::regclass)"))
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('order_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('contract_id_seq'::regclass)"))
        batch_op.alter_column('contract_consist_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('employee_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('driver_id_seq'::regclass)"))
        batch_op.drop_index('index_id_driver')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('employee_id_seq'::regclass)"))
        batch_op.alter_column('post',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('order_id_seq'::regclass)"))
        batch_op.alter_column('contract_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('warehouse_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('driver_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('prepayment',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index('index_contract_id_orders')
        batch_op.drop_index('index_driver_orders')
        batch_op.drop_index('index_orders_driver')
        batch_op.drop_index('index_status_orders')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('product_id_seq'::regclass)"))
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('warehouse_id_seq'::regclass)"))
        batch_op.alter_column('quantity',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('warehouse_id_seq'::regclass)"))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('product_id_seq'::regclass)"))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('index_status_orders', ['status'], unique=False)
        batch_op.create_index('index_orders_driver', ['status', 'id'], unique=False)
        batch_op.create_index('index_driver_orders', ['id', 'status'], unique=False)
        batch_op.create_index('index_contract_id_orders', ['contract_id'], unique=False)
        batch_op.alter_column('prepayment',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('driver_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('warehouse_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('contract_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('order_id_seq'::regclass)"))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('post',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('employee_id_seq'::regclass)"))

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.create_index('index_id_driver', ['id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('driver_id_seq'::regclass)"))

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('contract_consist_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('contract_id_seq'::regclass)"))

    with op.batch_alter_table('consist', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('order_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('data',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('consist_id_seq'::regclass)"))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('client_id_seq'::regclass)"))

    op.create_table('employee_copy',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('post', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=256), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
